### ISSUE TITLE
Comments not enabled at Disqus

### ISSUE THREAD

**Issue by peterdesmet** [atlantichabitatmodels/communityofpractice#4]
FYI, it seems you have enabled `comments=true` for e.g. https://atlantichabitatmodels.github.io/communityofpractice/blog/nsfraxinusnigra/ but there is an issue with the shortname at Disqus apparently.

**Comment by jocelynpender** [comment]
Thanks for letting me know. I didn't realize I had comments enabled, whoops. I've set `comments=false`.

**Comment by peterdesmet** [comment]
👍 You can also remove `comments` entirely
